# -*- coding: utf-8 -*-
"""Tarea3_NEAs_JRM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Glqb37cDRRKrJUeb52gLcFna-BXyLTr

<p>
<h1><b><center></center></b></h1>
</p>
<h1><b><center>Mecánica Celeste</center></b></h1>
<h2><b><center>Prof. Jorge I. Zuluaga</center></b></h1>
<h2><b><center>Tarea 3</center></b><h2>
<h3><b><center>Asteroides Cercanos a la Tierra y el CRTBP</center></b><h3>
<h5><center><b>Asignada</b>: 26 de febrero de 2025</center><h5>
<h5><center><b>Entrega</b>: 13 de marzo de 2025</center><h5>
</p>

<hr/>
<b>Nombre</b>: Juliana Ruiz Montoya
<br/>
<b>Cédula</b>: 1007435437
<br/>
<b>Última actualización</b>: 12 de marzo de 2025
<hr/>

## Enunciado

**Objetivo**: Vamos a estudiar la órbita osculatriz de los asteroides cercanos a la Tierra o NEAs y su descripción en términos del CRTBP.

**Procedimiento**:

1. En principio, un asteroide se considera *cercano a la Tierra* (o NEA, por su sigla en inglés, *Near Earth Asteroid*) si su órbita puede cruzar la órbita de la Tierra. Demuestre que para que la órbita de un asteroide cumpla está condición se debe dar que $q<Q_\oplus$  y que $Q>q_\oplus$, donde $q$ y $Q$ son las distancias al periapsis y al apoapsis de un cuerpo en una órbita.

2. Haga un gráfico en el plano $e$-$a$ (estando $e$, la excentricidad en el eje y, y $a$ el semiejemayor en el eje x). Que muestre las órbitas para las cuáles $q=Q_\oplus$, $Q=q_\oplus$ y que haga un sombreado de las órbitas que cumplen la condición de cruzar la órbita de la Tierra.

3. Una condición dinámica más precisa para definir cuando un asteroide es una NEA, consiste tiene que ver con la constante de Jacobi o equivalentemente con el parámetro de Tisserand asociado al sistema Sol-Tierra:

  $$
  T \equiv \frac{a_\oplus}{a}+2 \cos i \sqrt{\left(\frac{a}{a_\oplus}\right)\left(1-e^2\right)}
  $$
  o en términos del $a$ relativo del asteroide, $\bar{a}=a/a_\oplus$
  $$
  T \equiv \frac{1}{\bar{a}}+2 \cos i \sqrt{\bar{a}\left(1-e^2\right)}
  $$

  Demuestre que para asteroides con inclinación orbital $i=0$ la excentricidad de la órbita de los asteroides que tienen constante de Tisserand constante, $T$, cumple:

  $$
  e=\sqrt{1-\frac{1}{4 \bar{a}^3 \cos ^2 i}(T \bar{a}-1)^2}
  $$

4. Haga un gráfico en el diagrama $e-a$ que hizo en 2 mostrando la ubicación en el diagrama de las curvas definidas por la ecuación en 3, cuando $T=2.5, 3.0, 3.5$. Compare las curvas resultantes con las que obtuvo en el punto 2. ¿Qué observa?

5. En el archivo que encontrarán [este enlace](https://drive.google.com/file/d/1jKxVp8v-q4G11UVpy6wtoPYyv6VKNSLr/view?usp=sharing) están los elementos osculantes de más de 37000 NEAs conocidas.  Calcule para cada asteroide el parámetro de Tisserand. Dibuje la ubicación de estos asteroides en el diagrama $e-a$ incluyendo las curvas calculadas en 2 y 5. ¿Qué observa?.

6. **(Opcional)** Escoja de la base de datos de Asteroides todos los asteroides que tengan parámetro de Tisserand cercano de 3.0 y dibuje las órbitas de esos asteroides en el sistema rotante Sol-Tierra. Observe si existe alguna regularidad o si los asteroides tienen orbitas completamente arbitrarias.

**Resultados esperados**:

- Este notebook con el procedimiento matemáticos y numéricos debidamente comentados en celdas de texto y de código.

- En caso de utilizar ayudas como `ChatGPT` o códigos de `Stack Over Flow` debe citar debidamente la fuente, pero también entender a cabalidad el código, el profesor puede pedir justificación.

## Solución

### **Punto 1. Demostración $q<Q_\oplus$  y que $Q>q_\oplus$**

Un asteroide se considera cercano a la Tierra (Near Earth Asteroid, NEA) si su órbita cruza la órbita de la Tierra. Demostraremos que para que esto ocurra, se debe cumplir que:

$$ q \leq Q_\oplus \quad \text{y} \quad Q \geq q_\oplus$$

donde $q$ y $Q$ son el perihelio y el afelio del asteroide, mientras que $q_\oplus$ y $Q_\oplus$ son los correspondientes a la Tierra.

---

Primero se debe considerar la condición para que las órbitas crucen, debe existir un instante en el cual ambas tengan la misma distancia al sol, lo que significa que:

$$ r_\oplus = r $$

donde $r_\oplus$ representa la distancia radial de la Tierra en su órbita elíptica y $r$ representa la distancia radial del asteroide en su órbita elíptica.

Por otro lado, los valores extremos de las órbitas están definidos como:

- Para la Tierra: $q_\oplus$ y $Q_\oplus$ (periapsis y apoapsis)

- Para el asteroide: $q$ y $Q$  (periapsis y apoapsis)

Los valores que puede tomar $r$ están dentro del intervalo cerrado de la órbita del asteroide: $r \in [q,Q]$, análogamente para la tierra: $r_\oplus \in [q_\oplus,Q_\oplus]$.

Para que haya el cruce de órbitas, debe existir al menos un instante en el que:

$$ e \in [q_\oplus,Q_\oplus] \cap [q,Q] \neq 0$$

Esto quiere decir que la intersección de los intervalos no debe ser vacía.

Ahora, para garantizar que el asteroide efectivamente cruce la órbita terrestre en lugar de solo tocarla, es necesario considerar intervalos abiertos:

$$r \in (q,Q), \quad r_\oplus \in (q_\oplus,Q_\oplus)$$

La teoría de cotas superiores e inferiores nos dice que:


- El supremo del intervalo de la Tierra es $Q_\oplus$, que es la cota superior más pequeña posible para $r_\oplus$.
- El ínfimo del intervalo de la Tierra es $q_\oplus$, que es la cota inferior más grande posible para $r_\oplus$.
- Para que los intervalos se superpongan, el ínfimo del intervalo del asteroide $q$ debe ser menor o igual que el supremo de la Tierra $Q_\oplus$, y el supremo del asteroide $Q$ debe ser mayor o igual que el ínfimo de la Tierra $q_\oplus$:

$$ q \leq Q_\oplus \quad \text{y} \quad Q \geq q_\oplus$$

Si alguna de estas desigualdades es estricta $<$ o $>$, el asteroide efectivamente cruza la órbita de la Tierra. Si se cumplen con igualdad, solo la toca.

Se importan las librerías necesarias.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from ipywidgets import interact

"""Ahora, se quiere mostrar de forma gráfica que siempre se cumple que $ q \leq 1.017 $ y $ Q \geq 0.983$, la órbita del asteroide cruza con la órbita terrestre.

Para esto, primero se establecen los elementos orbitales de la tierra, junto con su periapsis y apoapsis. Además, se establecen los ángulos para graficar las órbitas, que va desde $0$ hasta $2\pi$.

"""

a_tierra = 1.0
e_tierra = 0.0167
q_tierra = a_tierra * (1 - e_tierra)
Q_tierra = a_tierra * (1 + e_tierra)
angulo = np.linspace(0, 2*np.pi, 300)

"""Luego, se define una función para graficar las órbitas de la Tierra y del asteroide, se establece que $q$ debe ser mayor a $Q$.

Se calcula el semieje mayor y la excentricidad del asteroide:

$$ a_{ast} = \frac{q+Q}{2} $$

$$ e_{ast} = \frac{Q-q}{q+Q} $$

Además, definimos la ecuación polar de la posición de la órbita de la Tierra y del asteroide, se almacenan en las variables `r_tierra` y `r_asteroide` con la siguiente ecuación:

$$ r = \frac{a(1-e^2)}{1+e \cos θ} $$

Luego, se hace una conversión de coordenadas polares a cartesianas para la posición $r$ de la tierra y del asteroide:

$$ x = r\cos θ, \quad y = r\sin θ $$

Por último, se grafica las órbitas de la Tierra con sus variables `x_tierra` y `y_tierra` y la del asteroide con sus variables `x_asteroide` y `y_asteroide`.

Con `plt.scatter` se añade la posición del sol en la coordenada $(0,0)$, y además se marca el periapsis y apoapsis para los dos cuerpos con las variables antes definidas de `q_tierra`, `Q_tierra`, `q_asteroide` y `Q_asteroide`.

A la gráfica se le añade un texto que indica cuando el asteroide cruza la órbita de la Tierra, se delimita con las desigualdades anteriormente demostradas.
"""

def graficar_orbitas(a_asteroide, e_asteroide):

    q_asteroide = a_asteroide * (1 - e_asteroide)
    Q_asteroide = a_asteroide * (1 + e_asteroide)

    r_tierra = (a_tierra * (1 - e_tierra**2)) / (1 + e_tierra * np.cos(angulo))
    r_asteroide = (a_asteroide * (1 - e_asteroide**2)) / (1 + e_asteroide * np.cos(angulo))

    x_tierra, y_tierra = r_tierra * np.cos(angulo), r_tierra * np.sin(angulo)
    x_asteroide, y_asteroide = r_asteroide * np.cos(angulo), r_asteroide * np.sin(angulo)

    plt.figure(figsize=(6, 6))
    plt.plot(x_tierra, y_tierra, label="Órbita de la Tierra", color="darkgreen")
    plt.plot(x_asteroide, y_asteroide, label="Órbita del asteroide", color="royalblue")

    plt.scatter(0, 0, color="yellow", s=100, edgecolors="orange", label="Sol")
    plt.scatter([q_tierra, -Q_tierra], [0, 0], color="darkgreen", s=50, label="q y Q de la Tierra")
    plt.scatter([q_asteroide, -Q_asteroide], [0, 0], color="royalblue", s=50, label="q y Q del Asteroide")

    if q_asteroide < Q_tierra and Q_asteroide > q_tierra:
        print("El asteroide cruza la órbita de la Tierra")
    else:
        print("El asteroide NO cruza la órbita de la Tierra")

    print('El periapsis q del asteroide es:', q_asteroide)
    print('El apoapsis Q del asteroide es:', Q_asteroide)

    plt.xlabel("Distancia (UA)")
    plt.ylabel("Distancia (UA)")
    plt.title("Cruce de Órbitas entre un Asteroide y la Tierra")
    plt.legend()
    plt.grid(True)
    plt.axis("equal")

"""Al gráfico se la añade un interact de la librería `from ipywidgets import interact` para poder observar mejor que siempre que un asteroide cruza la órbita terreste es porque pasa esta condición:

$$ q \leq Q_\oplus \quad \text{y} \quad Q \geq q_\oplus$$
"""

interact(graficar_orbitas, a_asteroide=(0.5, 3.0, 0.1), e_asteroide=(0.0, 1.0, 0.05));

"""### **Punto 2. Gráfico en el plano $e$-$a$**

Primero, se establecen los parámetros de la órbita terrestre en au:

$$ q_\oplus = a(1-e) $$

$$ Q_\oplus = a(1+e) $$

El semieje mayor de la tierra es $a_\oplus = 1.000$ au y la excenticidad es $e_\oplus = 0.0167$, en conclusión tenemos que:

$$ q_\oplus ≈ 0.983 au, \quad Q_\oplus ≈ 1.017 au $$

donde $q_\oplus$ corresponde a la distancia al periapsis y $Q_\oplus$ corresponde a la distancia al apoapsis de la tierra.

Además, se plantea un rango de valores para el semieje mayor desde 0.5 au hasta 3.0 au.
"""

q_tierra = 0.983
Q_tierra = 1.017

a_s = np.linspace(0.5, 3.0, 500)

"""Luego, tenemos las curvas de intersección orbital, son las distancias máximas y mínimas de un cuerpo en una órbita elíptica, las cuales están dada por las siguientes ecuaciones:

*  **Periapsis (distancia mínima):**

$$ q = \frac{p}{1+e} = a(1-e) $$

*  **Apoapsis (distancia máxima):**

$$ Q = \frac{p}{1-e} = a(1+e) $$

donde $a$ es el semieje mayor de la órbita y $e$ es la excentricidad de la órbita.

Para que un asteroide cruce la órbita de la Tierra se debe cumplir que $q<Q_\oplus$ y $Q>q_\oplus$.

De esta manera tenemos que:

1. **Curva de periapsis límite, $q=Q_\oplus$:**

$$ q = a(1-e) = Q_\oplus → e = 1- \frac{Q_\oplus}{a}$$

2. **Curva del apoapsis límite, $Q = q_\oplus$:**

$$ Q = a(1+e) = q_\oplus → e = \frac{q_\oplus}{a} - 1$$

Estas curvas representan el límite donde el periapsis del asteroide es igual al apoapsis de la Tierra; y el límite donde el apoapsis del asteroide es igual al periapsis de la Tierra.





"""

e_periapsis = 1 - Q_tierra / a_s
e_apoapsis = q_tierra / a_s - 1

"""Ahora, para graficar la zona sombreada de las órbitas que cumplen la condición de cruzar la órbita de la Tierra, usamos `np.meshgrid`, que genera una malla de puntos (en un plano de dos dimensiones), en este caso en el plano $e-a$; variamos los valores del semieje mayor entre 0.5 y 3, contenido en la variable `a_s` y para la excentricidad, asiganmos valores de 0 a 1.

Los valores de $a$ y $e$ para la región sombreada quedan almacenados en las variables `a_mesh` y `e_meash` respectivamente.

Luego, se calculan los valores de periapsis y apoapsis para cada punto de la malla usando las fórmulas para $q$ y $Q$ anteriormente descritas, y se almacenan los resultados en matrices de dos dimensiones en `q_s` y `Q_s` respectivamente.

Por último, se genera la máscara para la región sombreada que cumpla con $q<Q_\oplus$  y que $Q>q_\oplus$ y se almacena en la variable `mascara`.

---

Para el gráfico se usa plt.contourf para dibujar la región sombreada donde `mascara` sea True.

Y se grafica además las curvas límites descritas anteriormente.
"""

plt.figure(figsize=(6, 6))

a_mesh, e_mesh = np.meshgrid(a_s, np.linspace(0, 1, 500))
q_s = a_mesh * (1 - e_mesh)
Q_s = a_mesh * (1 + e_mesh)

mascara = (q_s < Q_tierra) & (Q_s > q_tierra)
plt.contourf(a_mesh, e_mesh, mascara, levels=[0.5, 1], colors=['lightgray'])

plt.plot(a_s, e_periapsis, 'r-', label=r'$q = Q_\oplus$')
plt.plot(a_s, e_apoapsis, 'b-', label=r'$Q = q_\oplus$')

plt.xlabel(r'Semieje mayor $a$ (UA)')
plt.ylabel(r'Excentricidad $e$')
plt.ylim(-0.2, 1)
plt.title('Órbitas que cruzan la órbita de la Tierra en el plano $e$-$a$')
plt.axhline(0, color='green', linewidth=2, label='$e = 0$')
plt.axvline(1, color='black', linestyle='--', linewidth=1, label=r'$a_\oplus = 1$')
plt.legend()
plt.grid()

"""La región sombreada del gráfico representa las órbitas que cruzan la órbita de la Tierra, estos objetos se denominan NEAs (Near Earth Asteroid).

### **Punto 3. Demostración parámetro de Tisserand**

Tenemos que el parámetro de Tisserand asociado al sistema Sol-Tierra está dado por:

$$ T = \frac{1}{\bar a} + 2 \cos i \sqrt{\bar a (1-e^2)} ~~~~~(1)$$

donde $\bar a = a/a_\oplus$.

Ahora, despejamos la excentricidad de la ecuación (1), desarrollando tenemos:

Restamos $1/\bar a$ en ambos lados

$$ T - \frac{1}{\bar a} = 2 \cos i \sqrt{\bar a (1-e^2)}$$

Luego, realizamos la resta del lado izquierdo y dividimos por $2 \cos i$ la ecuación:

$$ \frac{T\bar a - 1}{2 \bar a \cos i} = \sqrt{\bar a(1-e^2)} $$

Elevamos al cuadrado toda la expresión:

$$ \left(\frac{T\bar a - 1}{2 \bar a \cos i}\right)^2 = {\bar a(1-e^2)} $$

Despejamos $e^2$:

$$ 1 - e^2 = \frac{(T \bar a -1)^2}{4 \bar a^3 \cos^2 i} $$

$$ e^2 = 1- \frac{(T \bar a -1)^2}{4 \bar a^3 \cos^2 i} $$

Por último, aplicamos raíz cuadrada a ambos lados y despejamos $e$:

$$ e = \sqrt{1- \frac{(T \bar a -1)^2}{4 \bar a^3 \cos^2 i}} ~~~~~ (2)$$

Para asteroides con inclinación orbital  $i=0$  la excentricidad de la órbita de los asteroides que tienen constante de Tisserand constante, $T$, cumple la ecuación (2), si lo queremos hacer explícito cuando $i = 0 → \cos i = 0$ y así tenemos:

$$ e = \sqrt{1- \frac{(T \bar a -1)^2}{4 \bar a^3}} $$

### **Punto 4. Gráfico con la constante de Tisserand**

Al gráfico del punto 2 se le añadirán curvas de Tisserand, para esto usamos las ecuaciones demostradas en el punto 3:

  $$
  T \equiv \frac{a_\oplus}{a}+2 \cos i \sqrt{\left(\frac{a}{a_\oplus}\right)\left(1-e^2\right)}
  $$

En este caso, tomamos valores para el parámetro de $T = 1.5, 3.0, 3.5$ contenidos en la variable `T_s`, además asumimos una inclinación $i = 0$ para visualizar la relación entre $e$ y $a$, si la inclinación es nula, tratamos órbitas coplanares con la tierra; así la ecuación de Tisserand es (tomando $\bar{a}=a/a_\oplus$):

  $$
  T \equiv \frac{1}{\bar{a}}+2 \sqrt{\bar{a}\left(1-e^2\right)}
  $$

De este modo la ecuación para la excentricidad $e$ está dada por:

  $$
  e=\sqrt{1-\frac{1}{4 \bar{a}^3}(T \bar{a}-1)^2}
  $$
"""

T_s = [2.5, 3.0, 3.5]

"""Para graficar las curvas de Tisserand usamos la ecuación de la excentricidad dependiendo del semieje mayor y el parámetro de Tisserand que corresponde a la variable `e_tisserand`. Además, se crea una lista de colores para asignarle a cada curva.

Usamos un for para que recorra las listas de los valores de Tisserand y los colores asignados, el zip asigna a cada valor de $T$ un color de la lista de colores.

Además, se impone una condición en la que los valores de `e_tisserand` para evitar valores imaginarios; si el argumento de la raíz cuadrada es negativo, significa que no hay solución real para $e$ entonces se reemplazan estos valores por NaN (Not a Number) para que no se dibujen en el gráfico.

Por úlimo, se grafica los semiejes mayores `a_s` con respecto a los valores de excenticidad calculados en `e_tiserrand`.
"""

plt.figure(figsize=(6, 6))
plt.contourf(a_mesh, e_mesh, mascara, levels=[0.5, 1], colors=['lightgray'])
plt.plot(a_s, e_periapsis, 'r-', label=r'$q = Q_\oplus$')
plt.plot(a_s, e_apoapsis, 'b-', label=r'$Q = q_\oplus$')

colores = ['magenta', 'darkcyan', 'orange']
for T, color in zip(T_s, colores):
    e_tisserand = np.sqrt(1 - (1 / (4 * a_s**3)) * (T * a_s - 1)**2)
    e_tisserand[e_tisserand < 0] = 0
    plt.plot(a_s, e_tisserand, linestyle='dashed', color=color, label=f'T = {T}')

plt.xlabel(r'Semieje mayor $a$ (UA)')
plt.ylabel(r'Excentricidad $e$')
plt.ylim(-0.2, 1)
plt.title('Curvas de Tisserand en el diagrama $e$-$a$')
plt.axhline(0, color='green', linewidth=2, label='$e = 0$')
plt.axvline(1, color='black', linestyle='--', linewidth=1, label=r'$a_\oplus = 1$')
plt.legend()
plt.grid()

"""**Conclusión sobre las curvas de Tisserand en el diagram $e-a$**

- Las curvas de Tisserand no se extienden indefinidamente en $a$ porque la raíz cuadrada en su ecuación se vuelve negativa para ciertos valores de $a$, lo que significa que no hay soluciones reales para la excentricidad $e$, esto restringe las posibles órbitas que cumplen una determinada constante de Tisserand.

- Algunas curvas de Tisserand intersectan o se acercan a las curvas límites $q=Q_\oplus$ y $Q = q_\oplus$, lo que sugiere que los asteroides con ciertos valores de $T$ pueden o no cruzar la órbita terrestre.

- En particular, los valores de
$T$ más bajos tienden a permitir órbitas más excéntricas, lo que aumenta la probabilidad de intersección con la órbita de la Tierra. Por el contrario, para valores más alto de $T$, las órbitas posibles tienen menor excentricidad, lo que significa que están más limitadas en el eje $a$.

**¿Qué respresentan las curvas de Tisserand?**

- Cada curva representa órbitas con el mismo valor de $T$ (parámetro de Tisserand) en el sistema Sol-Tierra.

- En un sistema donde un pequeño cuerpo está influenciado por un planeta masivo, estas curvas ayudan a visualizar cómo ciertas órbitas están gravitacionalmente vinculadas a ese planeta sin necesariamente ser satélites.

### **Punto 5. Parámetro de Tisserand para NEAs**

Se usa el comando `!gdown` en Google Colab para descar el archivo que contiene los elementos orbitales de los NEAs mediante el id del archivo.
"""

!gdown --id 1jKxVp8v-q4G11UVpy6wtoPYyv6VKNSLr

"""Se carga el archivo CSV con los datos correspondientes de los NEAs, se lee el archivo y se guardan los datos en un DataFrame de pandas en la variable `df`."""

file = "NEAs-feb_26_2025.csv"
df = pd.read_csv(file)

"""Se extraen los datos necesarios de cada asteroide."""

e_asteroides = df['e']
a_asteroides = df['a']  # en UA

"""Ahora, se grafica la misma grafica obtenida en el punto 4, en el que vemos las curvas de Tisserand en el diagrama $e-a$, a este grafico se le añaden las posiciones de los asteroides cercanos a la Tierra.

Con `plt.scatter` graficamos cada asteroide como un punt para obtener un diagrama de dispersión, sus elementos orbitales $a$ y $e$ se extraen del dataframe.
"""

plt.figure(figsize=(6, 6))
plt.contourf(a_mesh, e_mesh, mascara, levels=[0.5, 1], colors=['lightgray'])
plt.plot(a_s, e_periapsis, 'r-', label=r'$q = Q_\oplus$')
plt.plot(a_s, e_apoapsis, 'b-', label=r'$Q = q_\oplus$')

for T, color in zip(T_s, colores):
    e_tisserand = np.sqrt(1 - (1 / (4 * a_s**3)) * (T * a_s - 1)**2)
    e_tisserand[e_tisserand < 0] = 0
    plt.plot(a_s, e_tisserand, linestyle='dashed', color=color, label=f'T = {T}')

plt.scatter(a_asteroides, e_asteroides, s=1, color="black", alpha=0.3, label="NEAs observados")

plt.xlabel(r'Semieje mayor $a$ (UA)')
plt.ylabel(r'Excentricidad $e$')
plt.xlim(0.3, 3)
plt.ylim(-0.1, 1)
plt.title('Ubicación de los NEAs en el diagrama $e$-$a$')
plt.legend()
plt.grid()

"""**Del diagrama se puede observar y concluir que:**

- La mayoría de los **NEAs** (puntos negros en el diagrama) se encuentran en la región sombreada o cerca, confirmando que efectivamente que algunos de ellos cruzan la órbita terrestre.

- Algunos asteroides se agrupan en ciertas zonas del diagrama $e-a$, lo que sugiere que hay patrones dinámicos que gobiernan su distribución; y se evidencia que no todos los NEAs tienen el mismo $T$, lo que tal vez indica una diversidad en sus orígenes y evolución orbital.

- El gráfico permite visualizar de manera clara cuáles asteroides pueden representar un riesgo de impacto con la Tierra, es útil para la clasificación dinámica de los NEAs y su relación con la Tierra.

- Los NEAs con valores de T similiares tienden a ubicarse en regiones cercanos dentro del diagrama.

**Comparación con la región sombreada de los NEAs**

No todas las órbitas que cruzan la Tierra tienen el mismo $T$, lo que indica que existen múltiples trayectorias dinámicas para NEAs.

Algunas curvas de $T$ intersectan la región sombreada (órbitas que cruzan la Tierra), lo que confirma que ciertos asteroides en esas curvas efectivamente cruzan la órbita terrestre.

### **Referencias**

[1] Zuluaga, J. I. (2024, abril). *Mecánica Celeste: Teoría, algoritmos y problemas.* Editorial Universidad de Antioquia.

[2] numpy.meshgrid — NumPy v2.2 Manual. (s.f.). https://numpy.org/doc/2.2/reference/generated/numpy.meshgrid.html

[3] matplotlib.pyplot.contourf — Matplotlib 3.10.1 documentation. (2012 - 2015). https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contourf.html

[4] Colaboradores de Wikipedia. (2024, 6 agosto). Elemento supremo e ínfimo. Wikipedia, la Enciclopedia Libre. https://es.wikipedia.org/wiki/Elemento_supremo_e_%C3%ADnfimo
"""